-- Create votes table for storing vote submissions

-- 1. Create the votes table
CREATE TABLE IF NOT EXISTS votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  voter_name TEXT NOT NULL,
  national_id TEXT NOT NULL UNIQUE,
  list_number INTEGER NOT NULL,
  candidate_number INTEGER NOT NULL,
  candidate_name TEXT NOT NULL,
  voted_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE votes ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS policies (adjust as needed based on your needs!
-- This policy allows anyone to insert (since this is a public voting simulator)
CREATE POLICY "Allow public insert on votes"
  ON votes
  FOR INSERT
  TO public
  WITH CHECK (true);

-- Optional: If you want to allow viewing votes (for admin purposes)
-- CREATE POLICY "Allow public select on votes"
--   ON votes
--   FOR SELECT
--   TO public
--   USING (true);
