-- ═══════════════════════════════════════════════════════════════════════
--  Oufia November — Full Supabase Schema
--  Run this in: Supabase Dashboard → SQL Editor → New Query
-- ═══════════════════════════════════════════════════════════════════════

-- ───────────────────────────────────────────────
-- 1. VOTES TABLE
-- ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS votes (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  voter_name       TEXT NOT NULL,
  national_id      TEXT NOT NULL UNIQUE,
  list_number      INTEGER NOT NULL,
  candidate_number INTEGER NOT NULL,
  candidate_name   TEXT NOT NULL,
  wilaya_code      INTEGER DEFAULT 40,
  wilaya_name      TEXT DEFAULT 'خنشلة',
  municipality_name TEXT,
  voted_at         TIMESTAMPTZ DEFAULT NOW(),
  created_at       TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE votes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public insert on votes" ON votes;
CREATE POLICY "Allow public insert on votes"
  ON votes FOR INSERT TO public WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public select on votes" ON votes;
CREATE POLICY "Allow public select on votes"
  ON votes FOR SELECT TO public USING (true);


-- ───────────────────────────────────────────────
-- 2. SETTINGS TABLE (single-row site config)
-- ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS settings (
  id                   INTEGER PRIMARY KEY DEFAULT 1,
  candidate_name       TEXT NOT NULL DEFAULT 'عماد رزايقية',
  candidate_name_en    TEXT NOT NULL DEFAULT 'Imad Rezayguia',
  list_number          INTEGER NOT NULL DEFAULT 102,
  candidate_number     INTEGER NOT NULL DEFAULT 2,
  vote_goal            INTEGER NOT NULL DEFAULT 2500,
  hero_portrait_url    TEXT DEFAULT '/candidate_portrait.png',
  facebook_url         TEXT DEFAULT 'https://facebook.com',
  twitter_url          TEXT DEFAULT 'https://twitter.com',
  youtube_url          TEXT DEFAULT 'https://youtube.com',
  footer_slogan_ar     TEXT DEFAULT 'إختاروا من يدافع عنكم فهو أصلا محام.',
  footer_slogan_en     TEXT DEFAULT 'November''s history liberated us, November''s future builds us.',
  updated_at           TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT settings_singleton CHECK (id = 1)
);

ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- Public can read settings
DROP POLICY IF EXISTS "Allow public select on settings" ON settings;
CREATE POLICY "Allow public select on settings"
  ON settings FOR SELECT TO public USING (true);

-- Public can update settings (demo mode — no auth required)
DROP POLICY IF EXISTS "Allow public update on settings" ON settings;
CREATE POLICY "Allow public update on settings"
  ON settings FOR UPDATE TO public USING (true) WITH CHECK (true);

-- Public can insert settings (for first-time seed)
DROP POLICY IF EXISTS "Allow public insert on settings" ON settings;
CREATE POLICY "Allow public insert on settings"
  ON settings FOR INSERT TO public WITH CHECK (true);


-- Seed default settings row (safe to run multiple times)
INSERT INTO settings (id) VALUES (1)
  ON CONFLICT (id) DO NOTHING;


-- ───────────────────────────────────────────────
-- 3. ARTICLES TABLE (bilingual news/blog posts)
-- ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS articles (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug         TEXT UNIQUE,
  title_ar     TEXT NOT NULL DEFAULT '',
  title_en     TEXT NOT NULL DEFAULT '',
  summary_ar   TEXT DEFAULT '',
  summary_en   TEXT DEFAULT '',
  body_ar      TEXT DEFAULT '',
  body_en      TEXT DEFAULT '',
  cover_url    TEXT DEFAULT '',
  published_at TIMESTAMPTZ DEFAULT NOW(),
  is_published BOOLEAN NOT NULL DEFAULT true,
  created_at   TIMESTAMPTZ DEFAULT NOW(),
  updated_at   TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE articles ENABLE ROW LEVEL SECURITY;

-- Public can read published articles
DROP POLICY IF EXISTS "Allow public select on articles" ON articles;
CREATE POLICY "Allow public select on articles"
  ON articles FOR SELECT TO public USING (true);

-- Public can insert articles (demo mode)
DROP POLICY IF EXISTS "Allow public insert on articles" ON articles;
CREATE POLICY "Allow public insert on articles"
  ON articles FOR INSERT TO public WITH CHECK (true);

-- Public can update articles (demo mode)
DROP POLICY IF EXISTS "Allow public update on articles" ON articles;
CREATE POLICY "Allow public update on articles"
  ON articles FOR UPDATE TO public USING (true) WITH CHECK (true);

-- Public can delete articles (demo mode)
DROP POLICY IF EXISTS "Allow public delete on articles" ON articles;
CREATE POLICY "Allow public delete on articles"
  ON articles FOR DELETE TO public USING (true);


-- ───────────────────────────────────────────────
-- 4. NEWSLETTER SUBSCRIBERS TABLE
-- ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS subscribers (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email        TEXT NOT NULL UNIQUE,
  subscribed_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE subscribers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public insert on subscribers" ON subscribers;
CREATE POLICY "Allow public insert on subscribers"
  ON subscribers FOR INSERT TO public WITH CHECK (true);


-- ───────────────────────────────────────────────
-- 5. AUTOMATIC STORAGE BUCKET SETUP & POLICIES
-- ───────────────────────────────────────────────

-- 1. Create storage bucket 'campaign-media' if it does not exist, and ensure it is public
INSERT INTO storage.buckets (id, name, public)
VALUES ('campaign-media', 'campaign-media', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- 2. Allow public access to view/download files in 'campaign-media'
DROP POLICY IF EXISTS "Allow public select on campaign-media" ON storage.objects;
CREATE POLICY "Allow public select on campaign-media" ON storage.objects
  FOR SELECT TO public USING (bucket_id = 'campaign-media');

-- 3. Allow public uploads (insert) to 'campaign-media'
DROP POLICY IF EXISTS "Allow public insert on campaign-media" ON storage.objects;
CREATE POLICY "Allow public insert on campaign-media" ON storage.objects
  FOR INSERT TO public WITH CHECK (bucket_id = 'campaign-media');

-- 4. Allow public updates (replace) to 'campaign-media'
DROP POLICY IF EXISTS "Allow public update on campaign-media" ON storage.objects;
CREATE POLICY "Allow public update on campaign-media" ON storage.objects
  FOR UPDATE TO public USING (bucket_id = 'campaign-media') WITH CHECK (bucket_id = 'campaign-media');

-- 5. Allow public deletion from 'campaign-media'
DROP POLICY IF EXISTS "Allow public delete on campaign-media" ON storage.objects;
CREATE POLICY "Allow public delete on campaign-media" ON storage.objects
  FOR DELETE TO public USING (bucket_id = 'campaign-media');
-- ═══════════════════════════════════════════════════════════════════════

-- ───────────────────────────────────────────────
-- 6. MIGRATION FOR GEOGRAPHICAL FIELDS (if tables already exist)
-- ───────────────────────────────────────────────
-- Run these lines if you already have the votes table created
-- ALTER TABLE votes ADD COLUMN IF NOT EXISTS wilaya_code INTEGER DEFAULT 40;
-- ALTER TABLE votes ADD COLUMN IF NOT EXISTS wilaya_name TEXT DEFAULT 'خنشلة';
-- ALTER TABLE votes ADD COLUMN IF NOT EXISTS municipality_name TEXT;


